---

# GLOBAL SENAITE CONFIGURATION
#
# You can overwrite each variable in your custom cofiguration file which is run
# _after_ the `senaite_pre_tasks.yml`.
#
# Please see `vagrant-playbook.yml` for a running example.


### SENAITE BASE ###
additional_system_packages: []

# APT update intervals (`/etc/apt/apt.conf.d/10periodic`)
apt_do_upgrade_now: 0
apt_update_package_lists: 1
apt_download_upgradable_packages: 1
apt_autocleaninterval: 7
apt_unattended_upgrade: 1
### SENAITE BASE ###


### SENAITE HAPROXY ###
haproxy_frontend_bind_address: "127.0.0.1"
haproxy_frontend_port: "8080"
haproxy_with_http_stats: no
haproxy_stats_user: admin
haproxy_stats_pass: admin
haproxy_frontend_id: senaite_frontend
haproxy_backend_id: senaite_backend
haproxy_backend_balance_method: leastconn
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'
### SENAITE HAPROXY ###


### SENAITE VARNISH ###
varnish_version: "4.0"
varnish_use_default_vcl: true
varnish_default_vcl_template_path: "../../templates/default.vcl.j2"
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "8080"
varnish_listen_port: "8888"
varnish_secret: "11bac9e6-1e39-4119-8078-974375b96c95"
varnish_config_path: /etc/varnish
varnish_admin_listen_host: "127.0.0.1"
varnish_admin_listen_port: "6082"
varnish_storage: "file,/var/lib/varnish/varnish_storage.bin,1024M"
###


### SENAITE NGINX ###
nginx_path: "/etc/nginx"
nginx_html_root: "/usr/share/nginx/senaite"
nginx_sites_available: "{{ nginx_path }}/sites-available"
nginx_sites_enabled: "{{ nginx_path }}/sites-enabled"
nginx_conf: "{{ nginx_path }}/nginx.conf"
nginx_extra_http_options: |
  proxy_read_timeout 1200s;

# VHOSTS
custom_vhosts:
  - senaite.local

# SSL
ssl_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_certificate_key: /etc/ssl/private/ssl-cert-snakeoil.key

# https://github.com/geerlingguy/ansible-role-nginx
nginx_remove_default_vhost: true
nginx_server_names_hash_bucket_size: "256"
nginx_client_max_body_size: "1024m"
nginx_gzip: "on"
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"
nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;
nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"
nginx_proxy_cache_path: ""
nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }
### SENAITE NGINX ###


### SENAITE PLONE ###
plone_version: '4.3.14'
plone_initial_password: admin
plone_instance_name: senaitelims
plone_site_id: senaitelims
plone_create_site: yes
plone_extra_find_links:
plone_buildout_cache_url: http://dist.plone.org/release/{{ plone_version }}/buildout-cache.tar.bz2
plone_group: senaite
plone_buildout_user: senaite
plone_daemon_user: senaite_daemon
plone_target_path: "/home/{{ plone_buildout_user }}"
plone_var_path: "/home/{{ plone_buildout_user }}/data"
plone_backup_path: no
plone_additional_eggs: []
plone_sources:
  - "bika.lims = git https://github.com/senaite/senaite.lims.git"
plone_zcml_slugs: []
plone_additional_versions:
  - zc.buildout=
  - setuptools=
plone_client_count: 2
plone_zserver_threads: 2
plone_zeo_ip: 127.0.0.1
plone_zeo_port: 8100
plone_client_base_port: 8081
plone_zodb_cache_size: 30000

# Supervisor Daemon HTTP
supervisor_with_http: yes
supervisor_http_port: "127.0.0.1:9001"
supervisor_http_user: "admin"
supervisor_http_pass: "admin"

# Zope Monitoring
monitoring_eggs:
  - Products.ZNagios
monitoring_zcml: []
monitoring_versions:
  - Products.ZNagios=0.7.2
zeo_monitor_port: 8999

# DB Pack
plone_pack_at:
  minute: 30
  hour: 1
  weekday: 7
plone_keep_days: 3

# DB Backup
plone_backup_at:
  minute: 30
  hour: 2
  weekday: "*"
plone_keep_backups: 5
plone_keep_blob_days: 21

# Final Plone config
senaite_plone_config:
  - plone_version: "{{ plone_version }}"
    plone_initial_password: "{{ plone_initial_password }}"
    plone_instance_name: "{{ plone_instance_name }}"
    plone_create_site: "{{ plone_create_site }}"
    plone_extra_find_links: "{{ plone_extra_find_links }}"
    plone_buildout_cache_url: "{{ plone_buildout_cache_url }}"
    plone_group: "{{ plone_group }}"
    plone_buildout_user: "{{ plone_buildout_user }}"
    plone_daemon_user: "{{ plone_daemon_user }}"
    plone_target_path: "{{ plone_target_path }}"
    plone_var_path: "{{ plone_var_path }}"
    plone_backup_path: "{{ plone_backup_path }}"
    plone_additional_eggs: "{{ plone_additional_eggs + monitoring_eggs }}"
    plone_sources: "{{ plone_sources }}"
    plone_zcml_slugs: "{{ plone_zcml_slugs + monitoring_zcml }}"
    plone_additional_versions: "{{ plone_additional_versions + monitoring_versions }}"
    plone_client_count: "{{ plone_client_count }}"
    plone_zserver_threads: "{{ plone_zserver_threads }}"
    plone_zeo_port: "{{ plone_zeo_port }}"
    plone_client_base_port: "{{ plone_client_base_port }}"
    plone_zodb_cache_size: "{{ plone_zodb_cache_size }}"
    plone_pack_at: "{{ plone_pack_at }}"
    plone_keep_days: "{{ plone_keep_days }}"
    plone_backup_at: "{{ plone_backup_at }}"
    plone_keep_backups: "{{plone_keep_backups }}"
    plone_keep_blob_days: "{{ plone_keep_blob_days }}"
### SENAITE PLONE ###
